### ISSUE TITLE
installation on mac OS

### ISSUE THREAD

**Issue by thibautlouis** [simonsobs/pixell#81] opened 2020-01-10 05:56 UTC
* pixell version: 0.7
* Python version: python 3
* Operating System: mac OS

### Description

We are trying to make pspy easily installable with pip, one of our dependency is pixell.
On mac I find that the compilation failed due to:

clang: cython/sharp.c
clang: error: unsupported option '-fopenmp'

This is due to the default use of clang as a c compiler.
It can easily be fixed that by adding:
os.environ["CC"] = "gcc"

in the setup.py (I added it line 17 but I don't think it matters).

This might be important if mac user experienced difficulties installing pixell.

**Comment by msyriac** [comment] 2020-01-10 14:03
Adding that line would override a potential user request through environment variables to, say, use Intel compilers. I also thought it wouldn't work in general since the name gcc on most Macs is just an alias for clang, but maybe you've set things up manually to prevent that after installing gcc?

Could definitely use your help here since neither Sigurd, Matthew nor I are Mac users.

**Comment by thibautlouis** [comment] 2020-01-10 16:43
I agree with both of your concerns and yes I have set up my gcc to be the real gcc.
I'm not sure on how to fix that in the general case, doesn't seem trivial to me.

**Comment by thibautlouis** [comment] 2020-01-21 07:18
I have installed pixell from scratch on a mac, here is what I had to to in case it is useful for another mac user. I have a mac OS catalina (but I'm confident it would work with any recent distribution):

Apple store : get or update Xcode (might take a while)
Install the macport corresponding to your python version : https://www.macports.org/


sudo port install python37
sudo port select --set python python37
sudo port install py37-ipython
sudo port select --set ipython py37-ipython
sudo port install py37-numpy py37-scipy py37-matplotlib 
sudo port select --set cython cython37
sudo port install py37-pip
sudo port select --set pip pip37

You will need a C/Fortran compiler

sudo port install gcc9
sudo port select --set gcc mp-gcc9
which gcc # it should print    
/opt/local/bin/gcc
if it doesn't close and open another terminal.

sudo port install automake autoconf  libtool
sudo pip install scipy==1.3.2 # 1.4 is not compatible with pyfftw yet
sudo pip install pyyaml 
sudo pip install Pillow
sudo pip install astropy==3.1.0 # Note that astropy 4 seems to induce a lof of warning and possibly problems
sudo pip install healpy


git clone https://github.com/simonsobs/pixell.git
sudo CC=gcc python setup.py build_ext -i
sudo CC=gcc python setup.py install
sudo python setup.py test

**Comment by thibautlouis** [comment] 2020-01-21 14:31
and just to be complete here is the doc we have included in pspy for the pixell installation on mac os:
https://github.com/simonsobs/pspy/blob/master/INSTALL_MACOS.rst

**Comment by msyriac** [comment] 2020-01-21 14:32
Nice! Thanks a lot for this -- I'll keep this issue open until we get pre-compiled binaries out.
If you can expand on "scipy 1.4 not compatible with pyfftw yet" and "Note that astropy 4 seems to induce a lot of warning and possibly problems.", that would be helpful; I use both scipy 1.4 and astropy 4 and haven't noticed any problems.

**Comment by thibautlouis** [comment] 2020-01-21 14:36
for scipy1.4 : https://github.com/pyFFTW/pyFFTW/issues/279
But pyfftw is a dependence of pspy, not sure about pixell.
for astropy4 let me report on this later, if you tell me it works for you, I should check again.

**Comment by msyriac** [comment] 2020-01-21 15:04
Ah ok, I can confirm the pyfftw issue.

**Comment by msyriac** [comment] 2021-07-17 00:41
@thibautlouis I'm closing this for now since we've had pre-compiled binaries for Macs for a while now (with a brief period of it being broken). This should be the preferred way of getting stuff to work on Macs (i.e. just do "pip install pixell --user" and let it fetch the right binary instead of compiling from scratch.

**Closed by msyriac** 2021-07-17 00:41 UTC
